### ISSUE TITLE
Scripts are loaded from 0.0.0.0 instead of 127.0.0.1

### ISSUE THREAD

**Issue by rmccue** [humanmade/react-wp-scripts#14]
The asset manifest is output with URLs like `http://0.0.0.0:3001/main.js`. This needs to translate the IP to the actual IP rather the IP binding it currently has.

**Comment by igmoweb** [comment]
I don't know if this is related but when I'm proxied to a secure server, the assets return an empty response.

**Comment by tfrommen** [comment]
This is the problem I'm having right now on Windows, yes.
I'll send a PR for this right away.
