### ISSUE TITLE
Images are not working in build

### ISSUE THREAD

**Issue by joelwolfgang** [humanmade/react-wp-scripts#32]
images in the src folder are linked /static/media/logo.[hash].svg. I can't get them to load correctly.

Unless I give them their full url: wp-content/themes/ etc.

**Comment by rmccue** [comment]
This is controlled by react-scripts' [`homepage`](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#building-for-relative-paths) setting, and you should set it the same as for create-react-app. There's no WP-specific behaviour around this :)
