### ISSUE TITLE
Catchable fatal error: Argument 1 passed to FOOBAR\get_assets_list()

### ISSUE THREAD

**Issue by AlanMc74** [humanmade/react-wp-scripts#40]
Getting this error when trying to setup react-wp-scripts in a wordpress plugin.

_Catchable fatal error: Argument 1 passed to FOOBAR\get_assets_list() must be an instance of FOOBAR\string, string given, called in /opt/lampp/htdocs/wordpress/wp-content/plugins/foobar/inc/react-wp/react-wp-scripts.php on line 139 and defined in /opt/lampp/htdocs/wordpress/wp-content/plugins/foobar/inc/react-wp/react-wp-scripts.php on line 41_

Setting up a small plugin that outputs a shortcode foobar, where I planned to output the react app. Any idea's what is going wrong? I had followed the instructions for setting it up.

**Comment by rmccue** [comment]
It sounds like you may be using an older version of PHP without [scalar type hints](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.scalar-type-declarations). PHP 7.0 is required for that.

**Comment by AlanMc74** [comment]
And that would be it alright, still using php 5.6.38 in my development environment, mainly as a lot of hosting companies haven't upgraded their shared hosting environments as of yet. Thanks for the quick response, if you do consider supporting below php 7.0 please do let me know.
