### ISSUE TITLE
PHP namespace argument does not update default ReactWPScripts

### ISSUE THREAD

**Issue by josephfusco** [humanmade/react-wp-scripts#41]
From within the plugin folder, running

```sh
npx create-react-app app --scripts-version react-wp-scripts --php-namespace="Masonite" .
```

does not update the default php namespace ReactWPScripts.

**Comment by roborourke** [comment]
Hi, I know this is realllly old now but I finally merged the CRAv2 branch (also fixed the eslint issue you mentioned there). Anyway, that should fix this problem now so I'll close this out. Feel free to reopen if this isn't the case.
